// Type declarations for virtual modules generated by @laravel/vite-plugin-wayfinder
// This file tells TypeScript about the `@/routes` virtual modules that Wayfinder
// provides at build/runtime so the language server stops reporting missing modules.

declare module "@/routes" {
    // The plugin generates multiple named exports (helpers that return route URLs).
    // We don't enforce precise types here — use `any` to silence the TS server.
    export const dashboard: (...args: any[]) => any;
    export const login: (...args: any[]) => any;
    export const register: (...args: any[]) => any;
    export const logout: (...args: any[]) => any;
    export const home: (...args: any[]) => any;
    export const send: (...args: any[]) => any;
    export const edit: (...args: any[]) => any;
    export const update: (...args: any[]) => any;
    export const store: (...args: any[]) => any;
    export const request: (...args: any[]) => any;
    export const email: (...args: any[]) => any;
    export const disable: (...args: any[]) => any;
    export const enable: (...args: any[]) => any;
    export const show: (...args: any[]) => any;
    export const product: (...args: any[]) => any;

    // Fallback for any other named export
    export const __any: any;
}

// Handle imports like `@/routes/some-subpath`
declare module "@/routes/*" {
    const whatever: any;
    export default whatever;
}
